name: igraph
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20200225.2
  - affine=2.3.0
  - argon2-cffi=20.1.0
  - arrow-cpp=2.0.0
  - async_generator=1.10
  - attrs=20.3.0
  - aws-c-common=0.4.59
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.10
  - aws-sdk-cpp=1.8.70
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - bokeh=2.2.3
  - boost-cpp=1.74.0
  - branca=0.4.1
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - cartopy=0.18.0
  - certifi=2021.5.30
  - cffi=1.14.4
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - contextily=1.0.1
  - cryptography=3.2.1
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - dill=0.3.3
  - distributed=2.30.1
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.9
  - feather-format=0.4.1
  - fiona=1.8.18
  - folium=0.11.0
  - freetype=2.10.4
  - freexl=1.0.5
  - fsspec=0.8.4
  - future=0.18.2
  - gdal=3.1.4
  - geographiclib=1.50
  - geojson=2.5.0
  - geopandas=0.8.1
  - geopy=2.0.0
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - glib=2.66.3
  - glog=0.4.0
  - grpc-cpp=1.33.2
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=67.1
  - idna=2.10
  - importlib-metadata=3.1.1
  - importlib_metadata=3.1.1
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jdcal=1.4.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab=2.2.9
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - kealib=1.4.13
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=10.0.1
  - libcurl=7.71.1
  - libffi=3.3
  - libflang=5.0.0
  - libgdal=3.1.4
  - libglib=2.66.3
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=12.3
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.0
  - libssh2=1.9.0
  - libthrift=0.13.0
  - libtiff=4.1.0
  - libutf8proc=2.6.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-meta=5.0.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mercantile=1.1.6
  - mistune=0.8.4
  - mkl=2020.4
  - msgpack-python=1.0.0
  - multiprocess=0.70.11.1
  - munch=2.5.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.3
  - networkx=2.5
  - notebook=6.1.5
  - numpy=1.19.4
  - olefile=0.46
  - openjpeg=2.3.1
  - openmp=5.0.0
  - openpyxl=3.0.5
  - openssl=1.1.1k
  - osmnx=0.16.2
  - packaging=20.4
  - pandas=1.1.4
  - pandoc=2.11.2
  - pandocfilters=1.4.2
  - parquet-cpp=1.5.1
  - parso=0.7.1
  - partd=1.1.0
  - pathos=0.2.7
  - patsy=0.5.1
  - pcre=8.44
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3
  - pixman=0.40.0
  - plotly=4.14.1
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - pox=0.2.9
  - ppft=1.6.6.3
  - proj=7.1.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - psutil=5.7.3
  - pyarrow=2.0.0
  - pycairo=1.20.0
  - pycparser=2.20
  - pygeos=0.8
  - pygments=2.7.2
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.12.3
  - pyrsistent=0.17.3
  - pyshp=2.1.2
  - pysocks=1.7.1
  - python=3.8.6
  - python-dateutil=2.8.1
  - python-igraph=0.8.3
  - python_abi=3.8
  - pytz=2020.4
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.12.9
  - qtconsole=5.0.1
  - qtpy=1.9.0
  - rasterio=1.1.8
  - rasterstats=0.14.0
  - re2=2020.11.01
  - requests=2.25.0
  - retrying=1.3.3
  - rioxarray=0.1.1
  - rtree=0.9.4
  - scikit-learn=0.24.0
  - scipy=1.5.3
  - seaborn=0.11.0
  - seaborn-base=0.11.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - simplejson=3.17.2
  - six=1.15.0
  - snappy=1.1.8
  - snuggs=1.4.7
  - sortedcontainers=2.3.0
  - sqlite=3.33.0
  - statsmodels=0.12.1
  - tblib=1.6.0
  - terminado=0.9.1
  - testpath=0.4.4
  - texttable=1.6.3
  - threadpoolctl=2.1.0
  - tiledb=2.1.3
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.61.2
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.0
  - widgetsnbextension=3.5.1
  - xarray=0.19.0
  - xerces-c=3.2.3
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
