name: ra2ce_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - conda-forge::rasterio
  - conda-forge::gdal=3.5.2
  - conda-forge::geos
  - conda-forge::fiona
  - poetry
  - gdal