name: ra2ce
channels:
  - conda-forge
  - defaults
dependencies:
  - affine
  - click
  - fiona
  - future
  - gdal
  - geojson
  - geopy
  - geopandas
  - networkx
  - numpy
  - osmnx=0.16.*
  - pandas
  - pyarrow
  - pytest
  - python=3.8.*
  - rasterio
  - rasterstats
  - rtree
  - scipy
  - seaborn
  - shapely
  - sphinx
  - tqdm
  - xarray
  - xlrd
  - openpyxl
