name: ra2ce
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.*
  - click=7.1.*
  - fiona=1.8.*
  - future=0.18.*
  - gdal=3.1.*
  - geojson=2.5.*
  - geopy=2.0.*
  - geopandas=0.8.*
  - networkx=2.5
  - numpy=1.19.*
  - osmnx=0.16.2
  - pandas=1.1.*
  - pyarrow=2.0.*
  - pytest=6.2.*
  - python=3.8.*
  - rasterio=1.1.*
  - rasterstats=0.14.*
  - rtree=0.9.*
  - scipy=1.5.*
  - seaborn=0.11.*
  - shapely=1.7.*
  - sphinx=4.5.*
  - tqdm=4.61.*
  - xarray=0.19.*
  - xlrd=1.2.*
  - openpyxl=3.0.*