name: ci-pull-request

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  CI:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          # use the latest mamba version
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          # always activate the ra2ce environment (name is specified in environment.yml)
          environment-file: environment.yml
          auto-activate-base: true
          activate-environment: ra2ce_env

      - name: Install Dependencies
        shell: pwsh
        run: |
          conda activate ra2ce_env
          poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Test with pytest
        shell: pwsh
        run: |
          conda activate ra2ce_env
          poetry run pytest