name: "Test docs branch"
on:
  - push

permissions:
    contents: write

jobs:
  docs:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    name: Checkout examples into separate directory.
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          # channels: conda-forge, nodefaults
          # channel-priority: strict
          environment-file: .config/environment.yml
          activate-environment: ra2ce_env

      - name: Install dependencies
        run: poetry install --without dev,test

      - name: Run sphinx
        run: poetry run ./docs/make html

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: test_docs
          FOLDER: docs\build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}