name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    # setup anaconda using mamba, a bit faster than with conda
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        # use the latest mamba version
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        # always activate the ra2ce environment (name is specified in environment.yml)
        activate-environment: ra2ce
        environment-file: environment.yml
    - name: Lint with flake8
      # use login shell so environment is activated
      shell: bash -l {0}
      run: |
        mamba install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      # use login shell so environment is activated
      shell: bash -l {0}
      run: |
        mamba install pytest
        pytest
